# Substitua SEU_USUARIO_OU_ORG pela sua organização/usuário no SonarCloud
sonar.projectKey=simple-task-api
sonar.organization=SEU_USUARIO_OU_ORG

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,infra/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
